### ISSUE TITLE
hex input for iv option problem

### ISSUE THREAD

**Issue by xTommyBoy** [1sis/Angecryption#2]
when we provide an hex input we got an error message i tested many ways 
with the original iv : 
![image](https://user-images.githubusercontent.com/66128183/218609316-33700caa-13e6-412c-97a2-556443dc33a0.png)
and with a hex conversion : 
![image](https://user-images.githubusercontent.com/66128183/218609177-3a14bfb1-4929-4f29-8e37-c755886e9eaa.png)
both didn't works

**Comment by 1sis** [comment]
Corrected.
